

// import { useState } from 'react';


// 
// export default function Flyer() {
//   const [flyers, setflyers] = useState(
//     FlyerData
//   );
// }

export const Flyer  = [
  { id:"001", phone: "9876543218", bulletin:"To live is the rarest thing in the world. Most people exist, that is all.", title:"Oscar Wilde" },
  { id:"002", phone: "9876543218", bulletin:"That it will never come again is what makes life so sweet.", title:"Emily Dickinson" },
  { id:"003", phone: "9876543218", bulletin:"It is never too late to be what you might have been.", title:"George Eliot" },
  { id:"005", phone: "9876543218", bulletin:"Pain is inevitable. Suffering is optional.", title:"Haruki Murakami" },
  { id:"006", phone: "9876543218", bulletin:"All the world's a stage, and all the men and women merely players.", title:"William Shakespeare" },
  { id:"007", phone: "9876543218", bulletin:"Be kind, for everyone you meet is fighting a hard battle.", title:"Plato" },
  { id:"008", phone: "9876543218", bulletin:"Unable are the loved to die for love is immortality.", title:"Emily Dickinson" },
  { id:"009", phone: "9876543218", bulletin:"Let me live, love, and say it well in good sentences.", title:"Sylvia Plath" },
  { id:"010", phone: "9876543218", bulletin:"Don't let your happiness depend on something you may lose.", title:"C.S. Lewis" },
  { id:"011", phone: "9876543218", bulletin:"We are all broken, that's how the light gets in.", title:"Ernest Hemingway" },
  { id:"012", phone: "9876543218", bulletin:"Appreciation is a wonderful thing. It makes what is excellent in others belong to us as well.", title:"Voltaire" },
  { id:"013", phone: "9876543218", bulletin:"Life is tough my darling, but so are you.", title:"Stephanie Bennett Henry" },
  { id:"014", phone: "9876543218", bulletin:"Self-awareness and self-love matter. Who we are is how we lead.", title:"Brene Brown" },
  { id:"015", phone: "9876543218", bulletin:"Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", title:"Stephen King" },
  { id:"017", phone: "9876543218", bulletin:"As a writer, you should not judge, you should understand.", title:"Ernest Hemingway" },
  { id:"018", phone: "9876543218", bulletin:"To produce a mighty book, you must choose a mighty theme.", title:"Herman Melville" },
  { id:"021", phone: "9876543218", bulletin:"The Six Golden Rules of Writing: Read, read, read, and write, write, write.", title:"Ernest Gaines" },
  { id:"025", phone: "9876543218", bulletin:"The purpose of a writer is to keep civilization from destroying itself.", title:"Albert Camus" },
  { id:"028", phone: "9876543218", bulletin:"A good writer possesses not only his own spirit but also the spirit of his friends.", title:"Friedrich Nietzsche" },
  { id:"030", phone: "9876543218", bulletin:"I am not at all in a humour for writing; I must write on until I am.", title:"Jane Austen" },
  { id:"032", phone: "9876543218", bulletin:"You can always edit a bad page. You can't edit a blank page.", title:"Jodi Picoult" },
  { id:"034", phone: "9876543218", bulletin:"If there's a book that you want to read, but it hasn't been written yet, then you must write it.", title:"Toni Morrison" },
  { id:"035", phone: "9876543218", bulletin:"Tears are words that need to be written.", title:"Paulo Coelho" },
  { id:"036", phone: "9876543218", bulletin:"You cannot find peace by avoiding life", title:"Virginia Woolf" },
  { id:"037", phone: "9876543218", bulletin:"The strongest principle of growth lies in the human choice", title:"George Eliot" },
  { id:"038", phone: "9876543218", bulletin:"Focus more on your desire than on your doubt, and the dream will take care of itself.", title:"Mark Twain" },
  { id:"045", phone: "9876543218", bulletin:"One day I will find the right words, and they will be simple.", title:"Jack Kerouac" },
  { id:"046", phone: "9876543218", bulletin:"I can be changed by what happens to me. But I refuse to be reduced by it.", title:"Maya Angelou" },
  { id:"047", phone: "9876543218", bulletin:"The most common way people give up their power is by thinking they don't have any.", title:"Alice Walker" },
  { id:"048", phone: "9876543218", bulletin:"I want to taste and glory in each day, and never be afraid to experience pain.", title:"Sylvia Plath" },
  { id:"049", phone: "9876543218", bulletin:"If I waited for perfection, I would never write a word.", title:"Margaret Atwood" },
  { id:"050", phone: "9876543218", bulletin:"How wonderful it is that nobody need wait a single moment before starting to improve the world.", title:"Anne Frank" },
  { id:"051", phone: "9876543218", bulletin:"We are what we repeatedly do. Excellence, then, is not an act, but a habit.", title:"Aristotle"}
]



export const CityData = [
  { id: "4", city_label: "Delhi", city_tier: "1" },
  { id: "1", city_label: "Ahmedabad", city_tier: "1" },
  { id: "2", city_label: "Bengaluru", city_tier: "1" },
  { id: "3", city_label: "Chennai", city_tier: "1" },
  { id: "5", city_label: "Hyderabad", city_tier: "1" },
  { id: "6", city_label: "Kolkata", city_tier: "1" },
  { id: "7", city_label: "Mumbai", city_tier: "1" },
  { id: "8", city_label: "Pune", city_tier: "1" },
  { id: "9", city_label: "Agra", city_tier: "2" },
  { id: "10", city_label: "Ajmer", city_tier: "2" },
  { id: "11", city_label: "Aligarh", city_tier: "2" },
  { id: "12", city_label: "Amravati", city_tier: "2" },
  { id: "13", city_label: "Amritsar", city_tier: "2" },
  { id: "14", city_label: "Anand", city_tier: "2" },
  { id: "15", city_label: "Asansol", city_tier: "2" },
  { id: "16", city_label: "Aurangabad", city_tier: "2" },
  { id: "17", city_label: "Bareilly", city_tier: "2" },
  { id: "18", city_label: "Belagavi", city_tier: "2" },
  { id: "19", city_label: "Bhavnagar", city_tier: "2" },
  { id: "20", city_label: "Bhilai", city_tier: "2" },
  { id: "21", city_label: "Bhiwandi", city_tier: "2" },
  { id: "22", city_label: "Bhopal", city_tier: "2" },
  { id: "23", city_label: "Bhubaneswar", city_tier: "2" },
  { id: "24", city_label: "Bikaner", city_tier: "2" },
  { id: "25", city_label: "Bilaspur", city_tier: "2" },
  { id: "26", city_label: "Bokaro Steel City", city_tier: "2" },
  { id: "27", city_label: "Chandigarh", city_tier: "2" },
  { id: "28", city_label: "Coimbatore", city_tier: "2" },
  { id: "29", city_label: "Cuttack", city_tier: "2" },
  { id: "30", city_label: "Dehradun", city_tier: "2" },
  { id: "31", city_label: "Dhanbad", city_tier: "2" },
  { id: "32", city_label: "Durgapur", city_tier: "2" },
  { id: "33", city_label: "Erode", city_tier: "2" },
  { id: "34", city_label: "Faridabad", city_tier: "2" },
  { id: "35", city_label: "Firozabad", city_tier: "2" },
  { id: "36", city_label: "Ghaziabad", city_tier: "2" },
  { id: "37", city_label: "Gorakhpur", city_tier: "2" },
  { id: "38", city_label: "Guntur", city_tier: "2" },
  { id: "39", city_label: "Gurugram", city_tier: "2" },
  { id: "40", city_label: "Guwahati", city_tier: "2" },
  { id: "41", city_label: "Gwalior", city_tier: "2" },
  { id: "42", city_label: "Hamirpur", city_tier: "2" },
  { id: "43", city_label: "Hubballi–Dharwad", city_tier: "2" },
  { id: "44", city_label: "Indore", city_tier: "2" },
  { id: "45", city_label: "Jabalpur", city_tier: "2" },
  { id: "46", city_label: "Jaipur", city_tier: "2" },
  { id: "47", city_label: "Jalandhar", city_tier: "2" },
  { id: "48", city_label: "Jalgaon", city_tier: "2" },
  { id: "49", city_label: "Jammu", city_tier: "2" },
  { id: "50", city_label: "Jamnagar", city_tier: "2" },
  { id: "51", city_label: "Jamshedpur", city_tier: "2" },
  { id: "52", city_label: "Jhansi", city_tier: "2" },
  { id: "53", city_label: "Jodhpur", city_tier: "2" },
  { id: "54", city_label: "Kakinada", city_tier: "2" },
  { id: "55", city_label: "Kalaburagi", city_tier: "2" },
  { id: "56", city_label: "Kannur", city_tier: "2" },
  { id: "57", city_label: "Kanpur", city_tier: "2" },
  { id: "58", city_label: "Karnal", city_tier: "2" },
  { id: "59", city_label: "Kochi", city_tier: "2" },
  { id: "60", city_label: "Kolhapur", city_tier: "2" },
  { id: "61", city_label: "Kollam", city_tier: "2" },
  { id: "62", city_label: "Kozhikode", city_tier: "2" },
  { id: "63", city_label: "Kurnool", city_tier: "2" },
  { id: "64", city_label: "Lucknow", city_tier: "2" },
  { id: "65", city_label: "Ludhiana", city_tier: "2" },
  { id: "66", city_label: "Madurai", city_tier: "2" },
  { id: "67", city_label: "Malappuram", city_tier: "2" },
  { id: "68", city_label: "Mangaluru", city_tier: "2" },
  { id: "69", city_label: "Mathura", city_tier: "2" },
  { id: "70", city_label: "Meerut", city_tier: "2" },
  { id: "71", city_label: "Moradabad", city_tier: "2" },
  { id: "72", city_label: "Mysuru", city_tier: "2" },
  { id: "73", city_label: "Nagpur", city_tier: "2" },
  { id: "74", city_label: "Nanded", city_tier: "2" },
  { id: "75", city_label: "Nashik", city_tier: "2" },
  { id: "76", city_label: "Nellore", city_tier: "2" },
  { id: "77", city_label: "Noida", city_tier: "2" },
  { id: "78", city_label: "Patna", city_tier: "2" },
  { id: "79", city_label: "Prayagraj", city_tier: "2" },
  { id: "80", city_label: "Puducherry", city_tier: "2" },
  { id: "81", city_label: "Purulia", city_tier: "2" },
  { id: "82", city_label: "Raipur", city_tier: "2" },
  { id: "83", city_label: "Rajamahendravaram", city_tier: "2" },
  { id: "84", city_label: "Rajkot", city_tier: "2" },
  { id: "85", city_label: "Ranchi", city_tier: "2" },
  { id: "86", city_label: "Ratlam", city_tier: "2" },
  { id: "87", city_label: "Rourkela", city_tier: "2" },
  { id: "88", city_label: "Salem", city_tier: "2" },
  { id: "89", city_label: "Sangli", city_tier: "2" },
  { id: "90", city_label: "Shimla", city_tier: "2" },
  { id: "91", city_label: "Siligphone", city_tier: "2" },
  { id: "92", city_label: "Solapur", city_tier: "2" },
  { id: "93", city_label: "Srinagar", city_tier: "2" },
  { id: "94", city_label: "Surat", city_tier: "2" },
  { id: "95", city_label: "Thanjavur", city_tier: "2" },
  { id: "96", city_label: "Thiruvananthapuram", city_tier: "2" },
  { id: "97", city_label: "Thrissur", city_tier: "2" },
  { id: "98", city_label: "Tiruchirappalli", city_tier: "2" },
  { id: "99", city_label: "Tirunelveli", city_tier: "2" },
  { id: "100", city_label: "Tiruvannamalai", city_tier: "2" },
  { id: "101", city_label: "Ujjain", city_tier: "2" },
  { id: "102", city_label: "Vadodara", city_tier: "2" },
  { id: "103", city_label: "Varanasi", city_tier: "2" },
  { id: "104", city_label: "Vasai-Virar", city_tier: "2" },
  { id: "105", city_label: "Vellore", city_tier: "2" },
  { id: "106", city_label: "Vijayapura", city_tier: "2" },
  { id: "107", city_label: "Vijayawada", city_tier: "2" },
  { id: "108", city_label: "Visakhapatnam", city_tier: "2" },
  { id: "109", city_label: "Warangal", city_tier: "2" }
  ]

export const LoveNote = [
{ id: "1", phone: "9876543210", color:"#fc5c6577", title:"Dear Dhanshree,", bulletin:"You are the best thing that has happended to me in a long long time. 😇" },
{ id: "2", phone: "9876543210", color:"#fd964477", title:"Babe,", bulletin:"You are the most amazing girl who has touched my heart and completely possessed it. 😍" },
{ id: "3", phone: "9876543210", color:"#fed33077", title:"Sweetheart,", bulletin:"You dont know how you make me weak in my knees. 🥰" },
{ id: "4", phone: "9876543210", color:"#26de8177", title:"Baby,", bulletin:"You are so beautiful you, give me butterlfies in the stomach. 😍" },
{ id: "5", phone: "9876543210", color:"#a55eea77", title:"Dear Girl,", bulletin:"You dont know how you rock my world. 🌏" },
{ id: "6", phone: "9876543210", color:"#2bcbba77", title:"You make me smile,", bulletin:"Not only you are beautiful but you are also so intelligent. 😘" },
{ id: "7", phone: "9876543210", color:"#fa823177", title:"Dear Love,", bulletin:"You are the last thing on my mind before I go to sleep. 🌓" },
{ id: "8", phone: "9876543210", color:"#4b658477", title:"And,", bulletin:"You are the first thing in my mind when I wake up. 🌞" },
{ id: "9", phone: "9876543210", color:"#2d98da77", title:"Everyday I wish,", bulletin:"That I get to hold you in my arms. 🤗" },
{ id: "10", phone: "9876543210", color:"#eb3b5a77", title:"And,", bulletin:"Kiss you again and again till we get tired. 💋" },
{ id: "11", phone: "9876543210", color:"#3867d677", title:"I have to say,", bulletin:"I miss you so much.😇" },
{ id: "12", phone: "9876543210", color:"#a5b1c277", title:"And my dear,", bulletin:"I love you so much.❤️" }

]


